site_name: Multitasking with Python
site_url: https://multitasking-with-python.joefaver.dev/
site_description: A Comprehensive Guide to Concurrency and Parallelism in Python for Data Scientists and Software Developers.
site_author: Joseph F. Vergel-Becerra

repo_url: https://github.com/joefavergel/multitasking-with-python
edit_uri: blob/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: pink
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: pink
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Introduction to Python Multitasking: python-multitasking.md
  - Concurrent Programming Walkthrough: concurrent-walkthrough.md
  - First Steps in Parallel Programming: parallel-walkthrough.md
  - About:
    - Release Notes: about/release-notes.md
    - License: about/license.md

extra_css:
  - css/extra.css

markdown_extensions:
  - toc:
      permalink: 
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.snippets
  - pymdownx.superfences

copyright: Copyright &copy; 2023 <a href="https://joefaver.dev">Joseph Vergel-Becerra</a>.
